force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <externalId>true</externalId>
    <label>CourseId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_Contact__c.field-meta.xml
<CustomField>
    <fullName>Student_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CourseHandler.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-10-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-08-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class CourseHandler {
    
    public void findCoursesByID(Map<String, Course__c> dataSource){

        for (Course__c course : [SELECT ID, courseId__c FROM Course__c WHERE courseId__c IN :dataSource.keySet()]) {
            dataSource.put(course.courseId__c, course);
        }
    }

    public Map<ID, List<Course__c>> findCoursesByStudent(Set<ID> students){

        Map<ID, List<Course__c>> result = new Map<ID, List<Course__c>>();

        for (Enrollment__c enr : [SELECT Course__r.ID, Course__r.Code__c, Course__r.Description__c,
                                         Student_Contact__c, Student_User__c 
                                  FROM   Enrollment__c 
                                  WHERE (Student_Contact__c IN :students OR Student_User__c IN :students)]) {

            ID student = enr.Student_Contact__c == null ? enr.Student_User__c : enr.Student_Contact__c;

            if (result.get(student) == null) result.put(student, new List<Course__c>{enr.Course__r});
            else result.get(student).add(enr.Course__r);
        }
 
        return result;
    }
}