force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/Learning_Plan_Course__c.object-meta.xml
<CustomObject>
    <label>Learning Plan Course</label>
    <nameField>
        <displayFormat>LPC-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LPC_Trigger_Manager.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-08-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-07-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class LPC_Trigger_Manager {
    
    public static void runBefore(List<Learning_Plan_Course__c> newData, Map<ID, Learning_Plan_Course__c> oldData) {
        
        Map<String, Learning_Plan__c> lnplanids = new Map<String, Learning_Plan__c>();
        Map<String, Course__c>        courseids = new Map<String, Course__c>       ();

        for (Learning_Plan_Course__c lpc : newData) {

            Learning_Plan_Course__c oldRecord = oldData == null ? null : oldData.get(lpc.ID);

            if (Trigger.isInsert || lpc.LearningPlanId__c != oldRecord.LearningPlanId__c  || lpc.courseId__c != oldRecord.courseId__c) {
                lnplanids.put(lpc.LearningPlanId__c, null);
                courseids.put(lpc.courseId__c,       null);
            }
        }

        if (!lnplanids.isEmpty() || !courseids.isEmpty()) reparent(newData, lnplanids, courseids);

        integrityControl(newData);
    }

    @testVisible
    private static void reparent(List<Learning_Plan_Course__c> newData, Map<String, Learning_Plan__c> lnplanids, Map<String, Course__c> courseids){

        List<Learning_Plan__c> lnplans = [SELECT ID, LearningPlanId__c FROM Learning_Plan__c WHERE LearningPlanId__c IN :lnplanids.keySet()];
        List<Course__c>        courses = [SELECT ID, courseId__c       FROM Course__c        WHERE courseId__c       IN :courseids.keySet()];

        for (Learning_Plan__c lp : lnplans) lnplanids.put(lp.LearningPlanId__c, lp);
        for (Course__c        cs : courses) courseids.put(cs.courseId__c,       cs);

        for (Learning_Plan_Course__c lpc : newData) {
            lpc.Learning_Plan__c = lnplanids.get(lpc.LearningPlanId__c).ID;
            lpc.Course__c        = courseids.get(lpc.courseId__c      ).ID;
        }
    }

    @testVisible
    private static void integrityControl(List<Learning_Plan_Course__c> newData) {

        for (Learning_Plan_Course__c lpc : newData) {
            if (lpc.Learning_Plan__c == null) { lpc.addError('Errore : non è stata trovata una corrispondenza per l\'ID : ' + lpc.LearningPlanId__c); continue; }
            if (lpc.Course__c        == null) { lpc.addError('Errore : non è stata trovata una corrispondenza per l\'ID : ' + lpc.courseId__c      ); continue; }
        }
    }
}