force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/Learning_Plan_Course__c.object-meta.xml
<CustomObject>
    <label>Learning Plan Course</label>
    <nameField>
        <displayFormat>LPC-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/LearningPlanEnrollment__c.object-meta.xml
<CustomObject>
    <label>LearningPlanEnrollment</label>
    <nameField>
        <displayFormat>LPE-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LearningPlanEnrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/idst__c.field-meta.xml
<CustomField>
    <fullName>idst__c</fullName>
    <externalId>true</externalId>
    <label>idst</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>LearningPlanEnrollments</relationshipLabel>
    <relationshipName>LearningPlanEnrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LPC_Trigger_Manager_Test.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-12-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-12-2020   f.ruggieri89@gmail.com   Initial Version
**/
@isTest
public with sharing class LPC_Trigger_Manager_Test {
    
    
    @TestSetup
    static void makeData(){

        insert new Learning_Plan__c(LearningPlanId__c = 'TEST');
        insert new Course__c(courseid__c = 'TEST');

        User u = [SELECT ID FROM User LIMIT 1];
        insert new LearningPlanEnrollment__c( idst__c = u.ID, LearningPlanId__c = 'TEST');
    }
    
    @isTest
    public static void test_trigger() {
        Learning_Plan__c lp = [SELECT ID FROM Learning_Plan__c LIMIT 1];
        Test.startTest();
        insert new Learning_Plan_Course__c(LearningPlanId__c = 'TEST', courseid__c = 'TEST');
        LPC_Trigger_Manager.ManageNewCoursePlan mncp = new LPC_Trigger_Manager.ManageNewCoursePlan(new Set<ID>{lp.ID});
        System.enqueueJob(mncp);
        Test.stopTest();
    }
}