force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <externalId>true</externalId>
    <label>CourseId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/Learning_Plan_Course__c.object-meta.xml
<CustomObject>
    <label>Learning Plan Course</label>
    <nameField>
        <displayFormat>LPC-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CourseHandler_Test.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-12-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-12-2020   f.ruggieri89@gmail.com   Initial Version
**/
@isTest
public with sharing class CourseHandler_Test {
    
    @TestSetup
    static void makeData(){
        Course__c c = new Course__c(courseId__c = 'TestData');
        insert c;
        User u = [SELECT ID FROM User LIMIT 1];

        TriggerManager.skipTrigger('Enrollment_Trigger');
        insert new Enrollment__c(Course__c = c.ID, Student_User__c = u.ID, idst__c = 'TEST', CourseId__c = 'TEST');

        Learning_Plan__c lp = new Learning_Plan__c(LearningPlanId__c = 'TEST');
        insert lp;

        TriggerManager.skipTrigger('LPC_Trigger');
        insert new Learning_Plan_Course__c(Learning_Plan__c = lp.ID, Course__c = c.ID);
    }

    @isTest
    public static void test_findCoursesByID() {
        String courseid = [SELECT courseId__c FROM Course__c LIMIT 1].courseId__c;
        Map<String, Course__c> data = new Map<String, Course__c>{courseid => null};
        Test.startTest();
        CourseHandler ch = new CourseHandler();
        ch.findCoursesByID(data);
        Test.stopTest();

        System.assert(data.get(courseid) != null, 'Record found');
    }

    @isTest
    public static void test_findCoursesByStudent(){
        ID userID = [SELECT Student_User__c FROM Enrollment__c LIMIT 1].Student_User__c;

        Test.startTest();
        CourseHandler ch = new CourseHandler();
        Map<ID, List<Course__c>> slc = ch.findCoursesByStudent(new Set<ID>{userID});
        Test.stopTest();

        System.assert(slc.get(userID) != null && !slc.get(userID).isEmpty(), 'Had results');
    }

    @isTest
    public static void test_findCoursesByLearningPlan() {
        ID lpID = [SELECT Learning_Plan__c FROM Learning_Plan_Course__c LIMIT 1].Learning_Plan__c;

        Test.startTest();
        CourseHandler ch = new CourseHandler();
        Map<ID, List<Course__c>> slc = ch.findCoursesByLearningPlan(new Set<ID>{lpID});
        Test.stopTest();

        System.assert(slc.get(lpID) != null && !slc.get(lpID).isEmpty(), 'Had results');
    }
}