force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <externalId>true</externalId>
    <label>CourseId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/DateCompleted__c.field-meta.xml
<CustomField>
    <fullName>DateCompleted__c</fullName>
    <label>DateCompleted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscribed</fullName>
                <default>true</default>
                <label>Subscribed</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_Contact__c.field-meta.xml
<CustomField>
    <fullName>Student_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/Courses_in_LP__c.field-meta.xml
<CustomField>
    <fullName>Courses_in_LP__c</fullName>
    <description>counts the courses per LP</description>
    <label>Courses in LP</label>
    <summaryForeignKey>Learning_Plan_Course__c.Learning_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/Learning_Plan_Course__c.object-meta.xml
<CustomObject>
    <label>Learning Plan Course</label>
    <nameField>
        <displayFormat>LPC-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/LearningPlanEnrollment__c.object-meta.xml
<CustomObject>
    <label>LearningPlanEnrollment</label>
    <nameField>
        <displayFormat>LPE-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LearningPlanEnrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/EnrollmentDate__c.field-meta.xml
<CustomField>
    <fullName>EnrollmentDate__c</fullName>
    <label>EnrollmentDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>LearningPlanEnrollments</relationshipLabel>
    <relationshipName>LearningPlanEnrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/Student_Contact__c.field-meta.xml
<CustomField>
    <fullName>Student_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LearningPlanEnrollments</relationshipLabel>
    <relationshipName>LearningPlanEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LearningPlanEnrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/studentviewer_CTRL.cls
/**
 * @description       : Visualforce component Controller class (StudentViewer.component)
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-12-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-11-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class studentviewer_CTRL {
    
    public Student_wrapper student {get; set{ Boolean changed = (value != student); student = value; setinfo(changed); }}

    /**
    * @description Student data are loaded only when passed from the main page
    * @author f.ruggieri89@gmail.com | 10-12-2020 
    * @param isChanged  Checks if the data received are new from the main page or simple rerender (avoid unnecessary logic)
    **/
    private void setInfo(Boolean isChanged){
        if (student != null && student.sf_id != null && isChanged) loadinfo();
    }

    /**
    * @description Fills the main student wrapper with every information needed to the FE
    * @author f.ruggieri89@gmail.com | 10-12-2020 
    **/
    private void loadinfo(){

        student.enrolledCourses = new Map<ID, Enrollment__c>();
        student.enrolledLplans = new Map<ID, LearningPlanEnrollment__c>();

        for (Enrollment__c e : [SELECT ID, Course__c, CourseId__c, EnrollmentDate__c, Status__c, DateCompleted__c FROM Enrollment__c WHERE (Student_Contact__c = :student.sf_id OR Student_User__c = :student.sf_id)]) {
            student.enrolledCourses.put(e.Course__c, e);
        }
        for (LearningPlanEnrollment__c l : [SELECT ID, Learning_Plan__c, LearningPlanId__c, EnrollmentDate__c FROM LearningPlanEnrollment__c WHERE (Student_Contact__c = :student.sf_id OR Student_User__c = :student.sf_id)]) {
            student.enrolledLplans.put(l.Learning_Plan__c, l);
        }

        student.courses = new Map<ID, Course__c>([SELECT ID, Name, Code__c, Description__c, courseId__c FROM Course__c WHERE ID IN :student.enrolledCourses.keySet()]);
        student.lPlans  = new Map<ID, Learning_Plan__c>([SELECT ID, Name, Code__c, Description__c, LearningPlanId__c, Courses_in_LP__c FROM Learning_Plan__c WHERE ID IN :student.enrolledLplans.keySet()]);
        student.lpCompledCourses = new Map<ID, Integer>();

        for (Learning_Plan_Course__c lpc : [SELECT Course__c, Learning_Plan__c FROM Learning_Plan_Course__c WHERE Learning_Plan__c IN :student.enrolledLplans.keySet()]){
            Integer total = student.lpCompledCourses.get(lpc.Learning_Plan__c) != null ? student.lpCompledCourses.get(lpc.Learning_Plan__c) : 0;
            if (student.enrolledCourses.get(lpc.Course__c) != null && 'Completed'.equalsIgnoreCase(student.enrolledCourses.get(lpc.Course__c).Status__c)) total++;
            student.lpCompledCourses.put(lpc.Learning_Plan__c, total);
        }

        student.lPlansPercentages = new Map<Id,Decimal>();
        for (Learning_Plan__c lp : student.lplansVal) {
            if (student.lpCompledCourses.get(lp.ID) == null) student.lpCompledCourses.put(lp.ID, 0);
            if (lp.Courses_in_LP__c == 0) student.lPlansPercentages.put(lp.ID, 100);
            else student.lPlansPercentages.put(lp.ID, (Decimal)((Decimal)student.lpCompledCourses.get(lp.ID) * 100 / (Decimal)lp.Courses_in_LP__c));
        }
    }
}