force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/Learning_Plan_Course__c.object-meta.xml
<CustomObject>
    <label>Learning Plan Course</label>
    <nameField>
        <displayFormat>LPC-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Learning Plan Courses</relationshipLabel>
    <relationshipName>Learning_Plan_Courses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Learning_Plan_Course__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/LearningPlanEnrollment__c.object-meta.xml
<CustomObject>
    <label>LearningPlanEnrollment</label>
    <nameField>
        <displayFormat>LPE-{00000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LearningPlanEnrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/idst__c.field-meta.xml
<CustomField>
    <fullName>idst__c</fullName>
    <externalId>true</externalId>
    <label>idst</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>LearningPlanEnrollments</relationshipLabel>
    <relationshipName>LearningPlanEnrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LearningPlanEnrollment__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/studentviewer_CTRL_Test.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-13-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-13-2020   f.ruggieri89@gmail.com   Initial Version
**/
@isTest
public with sharing class studentviewer_CTRL_Test {

    @TestSetup
    static void makeData(){

        ID userID = [SELECT ID FROM User LIMIT 1].ID;
        insert new Course__c(courseid__c = 'test_course');
        insert new Learning_Plan__c(learningplanid__c = 'test_lp');
        insert new Learning_Plan_Course__c(learningplanid__c = 'test_lp', courseid__c = 'test_course');
        insert new LearningPlanEnrollment__c(idst__c = userID, learningplanid__c = 'test_lp');
    }

    @isTest
    public static void test_controller() {
        Student_wrapper sw  = new Student_wrapper();
        sw.sf_id = [SELECT ID FROM User LIMIT 1].ID;
        sw.name  = 'TEST STUDENT';
        sw.type  = 'USER';

        Test.startTest();
        studentviewer_CTRL swc = new studentviewer_CTRL();
        swc.student = sw;
        Test.stopTest();

        System.assert(swc.student.coursesVal != null, 'Data correctly loaded');
        System.assert(swc.student.lPlansPercentages != null, 'Data correctly calculated');
    }
}