force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/courseId__c.field-meta.xml
<CustomField>
    <fullName>courseId__c</fullName>
    <externalId>true</externalId>
    <label>courseId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <externalId>true</externalId>
    <label>CourseId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_Contact__c.field-meta.xml
<CustomField>
    <fullName>Student_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Enrollment_Trigger_Manager.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-10-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-08-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class Enrollment_Trigger_Manager {

    public static CourseHandler  ch;
    public static StudentHandler sh;

    public static void runBefore(List<Enrollment__c> newData, Map<ID, Enrollment__c> oldData) {

        Map<String, SObject>   student = new Map<String, SObject>();
        Map<String, Course__c> courses = new Map<String, Course__c>();

        for (Enrollment__c enr : newData) {

            Enrollment__c oldRecord = oldData == null ? null : oldData.get(enr.ID);
            
            //Check if reparent is needed
            if (Trigger.isInsert || enr.idst__c != oldRecord.idst__c || enr.CourseId__c != oldRecord.CourseId__c) {
                student.put(enr.idst__c,     null);
                courses.put(enr.CourseId__c, null);
            }

            //Set enrollment date
            if (Trigger.isInsert && enr.EnrollmentDate__c == null) enr.EnrollmentDate__c = System.today();
        }

        if (!student.isEmpty()) reparent(newData, student, courses);
    }

    @testVisible
    private static void reparent(List<Enrollment__c> newData, Map<String, SObject> student, Map<String, Course__c> courses){

        ch = ch == null ? new CourseHandler()  : ch;
        sh = sh == null ? new StudentHandler() : sh;

        ch.findCoursesByID(courses);
        sh.findStudentsByID(student);

        for (Enrollment__c enr : newData) {
            //Reparent Courses
            enr.Course__c = courses.get(enr.CourseId__c) != null ? courses.get(enr.CourseId__c).ID : null;

            //Reparent Students
            if (String.isNotBlank(enr.idst__c)) {
                String key = enr.idst__c.left(15);
                if (key.startsWith('005') && student.get(key) != null) enr.Student_User__c = student.get(key).ID;
                else if (key.startsWith('002') && student.get(key) != null) enr.Student_Contact__c = student.get(key).ID;
            }
        }
    }
}