force-app/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Plan__c/fields/LearningPlanId__c.field-meta.xml
<CustomField>
    <fullName>LearningPlanId__c</fullName>
    <externalId>true</externalId>
    <label>LearningPlanId</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LearningPlanHandler.cls
/**
 * @description       : 
 * @author            : f.ruggieri89@gmail.com
 * @group             : 
 * @last modified on  : 10-08-2020
 * @last modified by  : f.ruggieri89@gmail.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   10-08-2020   f.ruggieri89@gmail.com   Initial Version
**/
public with sharing class LearningPlanHandler {
    
    public void findLearningplansByID(Map<String, Learning_Plan__c> dataSource){

        for (Learning_Plan__c lp : [SELECT ID, LearningPlanId__c FROM Learning_Plan__c WHERE LearningPlanId__c IN :dataSource.keySet()]) {
            dataSource.put(lp.LearningPlanId__c, lp);
        }
    }
}